[build]
    base='/'
    publish='dist'
    command='nuxt generate'
    environment = { NODE_VERSION = "20.10.0" }

[dev]                                          
   framework = "#custom"                                                    
   command = "npm run dev"             
   targetPort = 3000
   debug = true
   port = 8888
   publish = "dist"